<?php require VIEW_PATH . 'layouts/header.phtml'; ?>

<main class="container">
    <section class="container-fluid p-5 bg-light mb-3">
        <h1 class="display-5 fw-bold">
            <?php echo $this->title; ?>
        </h1>
        <p class="col-md-8 fs-4">
            <?php echo $this->description; ?>
        </p>
    </section>
    <section>
        <div class="row">
            <div class="col-md-4">
            <div class="">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d29517.371662737798!2d-92.37847850773335!3d38.955246034872005!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x87dcb7c0bd1d527f%3A0x69fafd501d12c2f!2sThe%20State%20Historical%20Society%20of%20Missouri%20Center%20for%20Missouri%20Studies!5e0!3m2!1spt-BR!2sbr!4v1652754841356!5m2!1spt-BR!2sbr" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
                <p>
                    <strong>
                        Telefone:
                    </strong>
                    <a href="tel:+(21) 2222-2222">(21) 2222-2222</a>
                </p>
                <p>
                    <strong>
                        E-mail:
                    </strong>
                    <a href="mailto:mail@exemple.com">mail@exemple.com</a>
                </p>
                <p>
                    <strong>
                        Endereço:
                    </strong>
                    <a href="https://goo.gl/maps/q4AqE8rDK7EnuxpE8" target="_blank" rel="noopener noreferrer">605 Elm St, Columbia, MO 65201, Estados Unidos</a>
                </p>
            </div>
            <div class="col-md-8">
                <form action="<?php route(CONTACT) ?>" method="post">
                    <div class="form-group">
                        <label for="name">Nome</label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="Nome">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="message">Mensagem</label>
                        <textarea class="form-control" id="message" name="message" rows="3"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>
            </div>
        </div>
    </section>
</main>

<?php require VIEW_PATH . 'layouts/footer.phtml'; ?>