<?php require VIEW_PATH . 'layouts/header.phtml'; ?>

<main class="container">
    <div class="container-fluid p-5 bg-light">
        <h1 class="display-5 fw-bold">
            <?php echo $_ENV['APP_NAME']; ?>
        </h1>
        <p class="col-md-8 fs-4">
            <?php echo $this->description; ?>
        </p>
        <button class="btn btn-primary btn-lg" type="button">
            Documentação
        </button>
    </div>
</main>

<?php require VIEW_PATH . 'layouts/footer.phtml'; ?>