<?php require VIEW_PATH . 'layouts/header.phtml'; ?>

<main class="container">
    <div class="container-fluid p-5 bg-light">
        <h1 class="display-5 fw-bold">
            <?php echo $this->title; ?>
        </h1>
        <p class="col-md-8 fs-4">
            <?php echo $this->description; ?>
        </p>
        <button class="btn btn-primary btn-lg" type="button">
            Documentação
        </button>
    </div>
    <h2 class="mt-3">
        Usuários que estão cadastrados
    </h2>
    <ul>
        <?php foreach ($this->users as $user): ?>
            <li>
                <?php echo $user['name']; ?> - <a href="/user/<?php echo $user['id']; ?>">Visualizar</a>
            </li>
        <?php endforeach; ?>
    </ul>
</main>

<?php require VIEW_PATH . 'layouts/footer.phtml'; ?>